# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

conda:
  environment: environment.yml
      
# Set the version of Python and other tools you might need
build:
  image: latest


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
